### ISSUE TITLE
sendToken does not work

### ISSUE THREAD

**Issue by RZeynalov** [kinfoundation/erc20token-sdk-python#13]
Hi Guyz,

The problem in _encode_transaction_data method, i guess new lib of web3 py has changed its methods, do you know how to fix it? Thx

PS: sendEther is working well

Traceback (most recent call last):
  File "/home/rashid/PycharmProjects/CryptiArbitrage/TestWeb3.py", line 21, in <module>
    print("send token ",sdk.send_tokens_new(address=Web3.toChecksumAddress(kukoinDadyWallet),amount=100))
  File "/home/rashid/PycharmProjects/CryptiArbitrage/walletman.py", line 219, in send_tokens_new
    hex_data2 = self.token_contract._encode_transaction_data('transfer', args=(address, self.web3.toWei(amount, 'ether')))
AttributeError: 'Contract' object has no attribute '_encode_transaction_data'

**Comment by theskumar** [comment]
Try with `web3==3.16.x`, the library is not compatible with version 4x of web3. 

```
pip install web3==3.16.5
```
